name: "github-action-go"
description: "An example of building github actions with Go"
inputs:
  message:
    required: true
runs:
  using: docker
  image: Dockerfile
  args:
    - ${{ inputs.message }}
